# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170815_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=200)),
                ('last_name', models.TextField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('birth', models.DateField(blank=True, null=True)),
                ('number', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('password1', models.TextField(max_length=500)),
                ('password2', models.TextField(max_length=500)),
            ],
        ),
    ]
