# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20170821_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='xxx@gmail.com', max_length=200),
        ),
    ]
