# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_remove_userprofile_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_read', 'Can Read Page'),),
            },
        ),
    ]
